from pathlib import Path

#DIRECTORIES
BASE_DIR = Path(__file__).resolve().parent.parent

ASSETS_DIR = BASE_DIR / "assets"

IMAGES_DIR = ASSETS_DIR / "images"
SOUNDS_DIR = ASSETS_DIR / "sounds"
FONTS_DIR = ASSETS_DIR / "fonts"

UI_IMAGES_DIR = IMAGES_DIR / "ui"
LOGOS_DIR = UI_IMAGES_DIR / "logos"

#TEMP DOWNLOADED ASSETS FOLDER
DOWNLOADED_ASSETS_DIR = ASSETS_DIR / "downloaded_from_online"
TINY_SWORDS_DIR = DOWNLOADED_ASSETS_DIR / "Tiny Swords (Free Pack)"

#UI ELEMENTS
UI_ELEMENTS_DIR = TINY_SWORDS_DIR / "UI Elements" / "UI Elements"

BUTTONS_DIR = UI_ELEMENTS_DIR / "Buttons"
PAPERS_DIR = UI_ELEMENTS_DIR / "Papers"

#TERRAIN
TERRAIN_DIR = TINY_SWORDS_DIR / "Terrain"
TILESET_DIR = TERRAIN_DIR / "Tileset"

#UNITS
UNITS_DIR = TINY_SWORDS_DIR / "Units"

BLACK_UNITS_DIR = UNITS_DIR / "Black Units"
BLACK_UNITS_WARRIOR_DIR = BLACK_UNITS_DIR / "Warrior"
BLACK_UNITS_ARCHER_DIR = BLACK_UNITS_DIR / "Archer"
BLACK_UNITS_ARCHER_ARROW_DIR = BLACK_UNITS_ARCHER_DIR / "Arrow.png"

RED_UNITS_DIR = UNITS_DIR / "Red Units"
RED_UNITS_WARRIOR_DIR = RED_UNITS_DIR / "Warrior"

BLUE_UNITS_DIR = UNITS_DIR / "Blue Units"
BLUE_UNITS_WARRIOR_DIR = BLUE_UNITS_DIR / "Warrior"
BLUE_UNITS_ARCHER_DIR = BLUE_UNITS_DIR / "Archer"
BLUE_UNITS_ARCHER_ARROW_DIR = BLUE_UNITS_ARCHER_DIR / "Arrow.png"

#ANIMATIONS
ANIMATION_FPS = 10 #10fps / 100ms

#CONSTANTS
WIDTH = 1600
HEIGHT = 1000
FPS = 60

TILE_SIZE = 128
GRASS_GREEN = (40, 120, 60)

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREY = (200, 200, 200)

g = 9.8
PROJECTILE_VELOCITY = 8

#DEBUG
HITBOXES = True